### ISSUE TITLE
Examples for "detectrealtime" and "eval" do not work

### ISSUE THREAD

**Issue by jingzbu** [hbhzwj/GAD#6]
```
./cmdgad detectrealtime -c ./example-configs/detect-config.py -d ./test-data/n0_flow.txt -m mfmb --srv=127.0.0.1:3000
```
## `--->TypeError: 'bool' object is not callable`

```
./cmdgad eval -c example-configs/eval-config.py --res_folder=res/ --ab_flows_data test-data/test_ab_flow.txt --plot
```

**Comment by jayjayram** [comment]
jingzbu I am also using SADIT and GAD softwares but I am getting error  in both  softwares that "socket.io clients nit foung " , Can u tell me how to solve this error. I don't know how to install socket.io but I follow commands mentioned in link https://pypi.python.org/pypi/socketIO-client
